name: Aurality Lab
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8900429087225348
title: Aurality Lab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#0e4152'
    - '#ffffff'
    - '#206a9a'
    - '#3dbcfe'
  brandStrength: 0.5625
  lightness: 0.4898146647028625
  saturation: 0.40684515866450965
  rhythmicContrast: 0.4169604417402297
purpose: []
